version: '3.4'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkd
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: unless-stopped
    ports:
      - "3306:3306"
    #volumes:
    # - ${PWD}/mariadb:/var/lib/mysql